export const DEPOSIT_REQUEST = "DEPOSIT_REQUEST";
export const DEPOSIT_SUCCESSFULL = "DEPOSIT_SUCCESSFULL";
export const DEPOSIT_FAILED = "DEPOSIT_FAILED";

export const WITHDRAW_REQUEST = "WITHDRAW_REQUEST";
export const WITHDRAW_SUCCESSFULL = "WITHDRAW_SUCCESSFULL";
export const WITHDRAW_FAILED = "WITHDRAW_FAILED";
